[package]
name = "bubshayz/windlines"
description = "Module for creating wind line effects."
authors = ["bubshayz", "boatbomber"]
version = "1.1.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.2.0"
Janitor = "howmanysmall/janitor@1.14.1"