[package]
name = "bubshayz/matrixutil"
description = "Utility module for working with matrixes."
authors = ["bubshayz"]
version = "1.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"