[package]
name = "bubshayz/numberutil"
description = "Utility module for working with numbers."
authors = ["bubshayz"]
version = "1.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"